### ISSUE TITLE
Change RangeType and JacobianRangeType?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-functions#39]
Currently, ``RangeType`` is ``FieldVector<dimRange>`` if ``dimRangeCols = 1`` and ``FieldMatrix<dimRange, dimRangeCols>`` for ``dimRangeCols > 1``. Likewise,  ``JacobianRangeType`` is either ``FieldMatrix`` or ``FieldVector<FieldMatrix<..>,..>``. While this is somewhat intuitive, especially in the usual case that ``dimRangeCols == 1``, this greatly complicates writing dimension-independent code in the finite volume case, where the flux functions' ``dimRangeCols`` is the space dimension. 

As we are changing all functions and interfaces by introducing bind of functions at the moment it would be a good opportunity to also change these types. I would propose to always use
``RangeType = FieldMatrix<dimRange, dimRangeCols>``
 and 
``JacobianRangeType = FieldVector<FieldMatrix<dimRange, dimDomain>, dimRangeCols>``,
also for ``dimRangeCols = 1``. That would allow to treat all dimensions equally and, due to the automatic conversion of ``FieldVector<R, 1>`` to ``R``, shouldn't complicate the ``dimRangeCols = 1`` case too much. 

What do you think, @dune-community/dune-xt-devs, @dune-community/dune-xt-contributors?

**Comment by ftalbrecht** [comment]
Unfortunately I disagree, since I think the special case `cols == 1` is the main case. But I will try to elaborate. Jumping ahead a bit: I think the main problem is here, that we try to use the same traits for data functions, solutions of a PDE and flux functions. Also, from your description: did you use the types in the old master as reference or the ones from the new master, in particular [this one](https://github.com/dune-community/dune-xt-functions/blob/new-master/dune/xt/functions/type_traits.hh#L129)?

For data functions (which do not depend on the solution) arising somewhere in a PDE, we usually have the following case: some physical domain `\Omega \subset R^d` and a function `\lambda: \Omega -> R^{r x c}`. Here the case `c != 1` is not unusual (think of anisotropic diffusion tensors in elliptic problems, often we have `\lambda: \Omega -> R^{d x d}`). In my experience, _data functions may be scalar, vector-valued or matrix-valued, and we only want to evaluate them, nearly never evaluate derivatives_. This case is nicely covered by the new [`RangeTypeSelector`](https://github.com/dune-community/dune-xt-functions/blob/new-master/dune/xt/functions/type_traits.hh#L45) and its specialization for `c == 1`.

On the other hand, a solution of a PDE, `u: \Omega -> R^{r x c}` is (always?) scalar or vector-valued. We do not even have discrete function spaces for the matrix valued case (Does anyone know of a case with matrix-valued solutions?). We want to evaluate those and need jacobians. However, in the case `c == 1`, there is a convention how a jacobian should look like, and we can find those hopefully in most math books. And that convention is `\nabla u: \Omega -> R^{r x d}`. So PDE solutions are covered by the `RangeTypeSelector<R, r, 1>` case and by the [`DerivativeRangeTypeSelector<..., 1>`](https://github.com/dune-community/dune-xt-functions/blob/new-master/dune/xt/functions/type_traits.hh#L155) case. _(See also my next comment)._

Now, there are also functions which depend on physical space and PDE solutions, and we called them fluxes. An example is the solution to the euler equations. Here we have a system of `m = d + 2` equations, thus the solution to the PDE is `u: \Omega -> R^m`. For every spatial variable `1 <= s <= d` we have an euler flux `f_s: R^m -> R^m` (they only depend on the solution, not some `x \in \Omega`, but that does not change anything). These Euler fluxes can be collected into a single flux `f: R^m -> R^{d x m}`. This is an example for a matrix-valued function and covered by the general `RangeTypeSelector` case. What we often need in finite volume code is an expression like
```
  \sum_{s = 1}^d \nabla f_s n_s
```
where `n_s` is a component of the spatial normal `n \in R^d`. The above sum can be interpreted as the dot product of _some jacobian of `f`_ and `n`, and we would like to write code such as `f.jacobian(u) * n`. For this to work we need to define the jacobian for the matrix-valued case exactly as we do in the general [`DerivativeRangeTypeSelector`](https://github.com/dune-community/dune-xt-functions/blob/new-master/dune/xt/functions/type_traits.hh#L122). Note that the type used here is
```
FieldVector<FieldMatrix<R, rC, d>, r>
```
but careful with the `d` here: this is the dimension of the fluxes domain, so `m` (the flux operates on the PDE solution, which is `m`-dimensional. So for the euler fluxes we have `d := m`, `r := d` and `rC := m`, which gives us
```
FieldVector<FieldMatrix<R, m, m>, d>
```
This is exactly what we need for the above expression, to get the fluxes jacobian times the normal as an `m x m` matrix.

So to sum up,
* data functions require `RangeTypeSelector<..., 1>` and `RangeTypeSelector`
* PDE solutions require `RangeTypeSelector<..., 1>` and `DerivativeRangeTypeSelector<..., 1>`
* fluxes require `RangeTypeSelector` and `DerivativeRangeTypeSelector`

That was my motivation for the choice of the traits, and I would like to keep them that way, if possible.  In particular I want to keep the `<..., 1>` special case for data functions and PDE solutions, as I think this is for most users the main use case. On the other hand I am quite fond of the general jacobian case for fluxes, as it makes for really nice code in fv schemes.

Perhaps we could discuss this further on an actual example, where this does not fit your needs? (I've heard its the affine function, if used as a flux function, not a data function). We could also discuss this further offline, if this goes too far...

**Comment by ftalbrecht** [comment]
What I forgot to mention above: in the case of the PDE solution `u: \Omega -> R^r` and its gradient `\nabla u: \Omega -> R^{r x d}`, if we would drop the specialization of `DerivativeRangeTypeSelector` and use the unspecialized one, this would give us:
```
FieldVector<FieldMatrix<R, 1, d>, r>
```
So in this case we would not benefit from any simplifications of `FieldVector<..., 1>` (which is the reason I asked above if you looked at the old or the new definition). So in the scalar and vector-valued case, the general `DerivativeRangeTypeSelector` really gives a very unintuitive jacobian for PDE solutions (these jacobians are used everywhere outside the FV case).

**Comment by tobiasleibner** [comment]
I used the types from the old master, for the new master I agree with your argumentation. Closing this.
